### ISSUE TITLE
Tests

### ISSUE THREAD

**Issue by Chumi-sun** [darroyue/IIC2283#4]
¿Se podrán probar los tests antes de la entrega de la tarea como en edd? ¿Hay fecha para su liberación?

**Comment by festelle** [comment]
Si no se podrá probar con los mismos tests, es posible que se nos pueda entregar algunos tests más que sean tan complejos como los que se usarán para evaluar?

**Comment by ricardor4** [comment]
Estimado,

**Al igual** que en el curso que señalas, tenemos tests públicos que son los del enunciado y una batería de test privados que se usarán para evaluar. Esto es exactamente la misma manera en que se evalúa en EDD, lo que confirmé con miembros del equipo docente de ese curso.


Saludos
Ricardo
